//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Exams')
export class ExamsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('date', { nullable: true })
  ExamDate: Date;

  @Column('integer', { nullable: true })
  TotalMarks: number;
}
