//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  StudentsList,
  StudentsCreate,
  StudentsEdit,
} from './resources/Students';
import { CoursesList, CoursesCreate, CoursesEdit } from './resources/Courses';
import { ExamsList, ExamsCreate, ExamsEdit } from './resources/Exams';
import {
  DailyPracticeProblemsList,
  DailyPracticeProblemsCreate,
  DailyPracticeProblemsEdit,
} from './resources/DailyPracticeProblems';
import { ResultsList, ResultsCreate, ResultsEdit } from './resources/Results';
import StudentsIcon from '@mui/icons-material/Person';
import CoursesIcon from '@mui/icons-material/Book';
import ExamsIcon from '@mui/icons-material/EventNote';
import DailyPracticeProblemsIcon from '@mui/icons-material/Assignment';
import ResultsIcon from '@mui/icons-material/Assessment';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/af1e469f5">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Students"
          options={{ label: 'Students' }}
          list={StudentsList}
          create={StudentsCreate}
          edit={StudentsEdit}
          recordRepresentation="Name"
          icon={StudentsIcon}
        />
        <Resource
          name="Courses"
          options={{ label: 'Courses' }}
          list={CoursesList}
          create={CoursesCreate}
          edit={CoursesEdit}
          recordRepresentation="Name"
          icon={CoursesIcon}
        />
        <Resource
          name="Exams"
          options={{ label: 'Exams' }}
          list={ExamsList}
          create={ExamsCreate}
          edit={ExamsEdit}
          recordRepresentation="ExamDate"
          icon={ExamsIcon}
        />
        <Resource
          name="DailyPracticeProblems"
          options={{ label: 'Daily Practice Problems' }}
          list={DailyPracticeProblemsList}
          create={DailyPracticeProblemsCreate}
          edit={DailyPracticeProblemsEdit}
          recordRepresentation="ProblemStatement"
          icon={DailyPracticeProblemsIcon}
        />
        <Resource
          name="Results"
          options={{ label: 'Results' }}
          list={ResultsList}
          create={ResultsCreate}
          edit={ResultsEdit}
          recordRepresentation="ResultID"
          icon={ResultsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
