//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Students: [
      {
        Name: 'Name 1',
        Gmail: 'Gmail 1',
        DateOfBirth: '2024-10-07T15:33:24.240Z',
        Number: 1,
        Class: 'Class 1',
        id: 37,
      },
      {
        Name: 'Name 2',
        Gmail: 'Gmail 2',
        DateOfBirth: '2024-07-01T12:30:50.021Z',
        Number: 2,
        Class: 'Class 2',
        id: 0,
      },
      {
        Name: 'Name 3',
        Gmail: 'Gmail 3',
        DateOfBirth: '2025-02-06T07:16:33.029Z',
        Number: 3,
        Class: 'Class 3',
        id: 93,
      },
      {
        Name: 'Name 4',
        Gmail: 'Gmail 4',
        DateOfBirth: '2023-05-31T07:33:32.536Z',
        Number: 4,
        Class: 'Class 4',
        id: 74,
      },
      {
        Name: 'Name 5',
        Gmail: 'Gmail 5',
        DateOfBirth: '2024-08-15T23:20:26.758Z',
        Number: 5,
        Class: 'Class 5',
        id: 68,
      },
    ],
    Courses: [
      { Name: 'Name 1', Description: 'Description 1', id: 82 },
      { Name: 'Name 2', Description: 'Description 2', id: 39 },
      { Name: 'Name 3', Description: 'Description 3', id: 71 },
      { Name: 'Name 4', Description: 'Description 4', id: 81 },
      { Name: 'Name 5', Description: 'Description 5', id: 21 },
    ],
    Exams: [
      { ExamDate: '2023-11-12T04:45:44.623Z', TotalMarks: 1, id: 47 },
      { ExamDate: '2024-03-17T16:56:23.810Z', TotalMarks: 2, id: 84 },
      { ExamDate: '2024-09-14T02:18:56.356Z', TotalMarks: 3, id: 96 },
      { ExamDate: '2023-05-27T23:25:13.284Z', TotalMarks: 4, id: 29 },
      { ExamDate: '2023-08-31T21:59:09.329Z', TotalMarks: 5, id: 71 },
    ],
    DailyPracticeProblems: [
      { ProblemStatement: 'ProblemStatement 1', id: 67 },
      { ProblemStatement: 'ProblemStatement 2', id: 54 },
      { ProblemStatement: 'ProblemStatement 3', id: 19 },
      { ProblemStatement: 'ProblemStatement 4', id: 12 },
      { ProblemStatement: 'ProblemStatement 5', id: 38 },
    ],
    Results: [
      { ResultID: 'ResultID 1', id: 27 },
      { ResultID: 'ResultID 2', id: 93 },
      { ResultID: 'ResultID 3', id: 99 },
      { ResultID: 'ResultID 4', id: 33 },
      { ResultID: 'ResultID 5', id: 65 },
    ],
  },
};
export default data;
