//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Students: {
      name: 'Students',
      fields: {
        Name: 'Name',
        Gmail: 'Gmail',
        DateOfBirth: 'Date Of Birth',
        Number: 'Number',
        Class: 'Class',
        id: 'id',
      },
    },
    Courses: {
      name: 'Courses',
      fields: { Name: 'Name', Description: 'Description', id: 'id' },
    },
    Exams: {
      name: 'Exams',
      fields: { ExamDate: 'Exam Date', TotalMarks: 'Total Marks', id: 'id' },
    },
    DailyPracticeProblems: {
      name: 'Daily Practice Problems',
      fields: { ProblemStatement: 'Problem Statement', id: 'id' },
    },
    Results: { name: 'Results', fields: { ResultID: 'Result Id', id: 'id' } },
  },
};
const frResources = {
  resources: {
    Students: {
      name: 'Students (fr)',
      fields: {
        Name: 'Name (fr)',
        Gmail: 'Gmail (fr)',
        DateOfBirth: 'Date Of Birth (fr)',
        Number: 'Number (fr)',
        Class: 'Class (fr)',
        id: 'id',
      },
    },
    Courses: {
      name: 'Courses (fr)',
      fields: { Name: 'Name (fr)', Description: 'Description (fr)', id: 'id' },
    },
    Exams: {
      name: 'Exams (fr)',
      fields: {
        ExamDate: 'Exam Date (fr)',
        TotalMarks: 'Total Marks (fr)',
        id: 'id',
      },
    },
    DailyPracticeProblems: {
      name: 'Daily Practice Problems (fr)',
      fields: { ProblemStatement: 'Problem Statement (fr)', id: 'id' },
    },
    Results: {
      name: 'Results (fr)',
      fields: { ResultID: 'Result Id (fr)', id: 'id' },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
